name: Artifacts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Compile Java
        run: |
          mkdir -p out
          javac -d out $(find . -name "*.java")

      - name: Create JAR Package
        run: |
          jar cvf SDP-Invaders.jar -C out/ .

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SDP-Invaders-jar
          path: SDP-Invaders.jar